name: CI for Java Invoice
on: [push]
jobs:
  lint:
    name: Lint code using checkstyle
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '15'
          distribution: 'adopt'
      - name: Checkstyle
        run: mvn checkstyle:check

  test:
    name: Unit tests on JDK ${{ matrix.version }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: [ 8, 13, 15 ]
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '15'
          distribution: 'adopt'
      - name: Test
        run: mvn test
      - name: Static Analysis
        run:  mvn checkstyle:check
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.version }}
