name: CI for Java Invoice
on: [push]
jobs:
  test:
    name: Unit tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '15'
          distribution: 'adopt'
      - name: Test
        run: mvn test
      - name: Static Analysis
        run:  mvn checkstyle:check
  matrix:
    strategy:
      runs-on: ubuntu-latest
      matrix:
        version: [ 8, 13, 15 ]
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.version }}
